### ISSUE TITLE
Practica 01: Prototipo

### ISSUE THREAD

**Issue by Lissete7** [SistemasTecTlaxiaco/practicaprototipos-equipoxd#2]
Link de la interfaz en adode XD:
https://xd.adobe.com/view/3119d070-0b9d-4d8b-8abd-2d1258dde865-644a/

Reporte de práctica: 
[Practica01 Prototipos_EquipoXD.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-equipoxd/files/6106389/Practica01.Prototipos_EquipoXD.pdf)

**Comment by garaudy12** [comment]
Calificación: 19 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
