### ISSUE TITLE
Calificación 19 puntos

### ISSUE THREAD

**Issue by garaudy12** [SistemasTecTlaxiaco/practicaprototipos-equipoxd#3]

**Comment by josealfredo79** [comment]
No hay reporte

**Comment by josealfredo79** [comment]
No hay reporte

**Comment by josealfredo79** [comment]
No se puede evaluar si no hay reporte

**Comment by josealfredo79** [comment]
no hay nada

**Comment by josealfredo79** [comment]
no hay nada

**Comment by Lissete7** [comment]
[Unidad1_Topicos_InterfazCalculadoraReporte.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-equipoxd/files/6749647/Unidad1_Topicos_InterfazCalculadoraReporte.pdf)

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado

**Comment by christopheremv** [comment]
calificación 19 de 20
