### ISSUE TITLE
Reporte practica3

### ISSUE THREAD

**Issue by Yeim1129** [SistemasTecTlaxiaco/practicaprototipos-equipoxd#4]
[Unidad1_Topicos_InterfazCalculadoraReporte.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-equipoxd/files/6191317/Unidad1_Topicos_InterfazCalculadoraReporte.pdf)

**Comment by josealfredo79** [comment]
Esta practica no tiene indice de figuras, tampoco tiene objetivo ni resultados.
